### ISSUE TITLE
Drivebase wheel position 

### ISSUE THREAD

**Issue by DKassab1425** [errorcodexero/swimmy2023#14]
After enabling the robot, the wheel angles are often messed up. The robot will fix itself after letting it sit for ~10 seconds although this slows down testing and drive practice

**Comment by sjcbulldog** [comment]
I have added a way for the top level robot code in instruct the swerve modules to reset their encoder positions.  This can be called when the robot is disabled during the swerve subsystem compute state method.  This should eliminate some of the arbitrary rotation of the swerve modules and should eliminate the 10 seconds (its really 5 seconds) delay that we must wait after resetting robot code.

**Comment by sjcbulldog** [comment]
This has been added to the test list for tonight (3/2).
