### ISSUE TITLE
Low cube scoring not returning control to driver 

### ISSUE THREAD

**Issue by DKassab1425** [errorcodexero/swimmy2023#15]
After scoring a cube in the low middle and low left position, control was not returned to the driver after the action had completed. We have not tested low right with a cube although cones seem to work everywhere.

**Comment by littlebunnie** [comment]
Aborting didn't seem to solve the problem either. We could try turtle mode.

**Comment by sjcbulldog** [comment]
Fixed, added to test list for Thursday 3/2.
