### ISSUE TITLE
new sensors on grabber

### ISSUE THREAD

**Issue by aditi-bhaskar** [errorcodexero/swimmy2023#33]
there is a left and right ir sensor, which still need to be wired in. (as of mar 18 2023)

include them in game piece detection code for ground ad station collect modes

once the sensors are wired in, these should be used (only) for cube collection, because that's where the incapability to detect is most noticeable. maybe also apply for the cones.

**Comment by sjcbulldog** [comment]
We have decided not to add these sensors.
