### ISSUE TITLE
grabber open position (maybe)

### ISSUE THREAD

**Issue by aditi-bhaskar** [errorcodexero/swimmy2023#34]
depending on how mechanical fixes the wobbly-grabber issue (wherein the grabber is laterally wobbly at any open position and has issues with self-detection), open the grabber wider, especially for cubes, to ease the ground collection action.

maybe we don't need to make the ground collect grabber position wider; it depends on whether or not the grabber works as intended

**Comment by sjcbulldog** [comment]
Mechanical added a chain tension device to reduce this.  Grabber positions have been tuned to optimize our ability to grab gamepieces.
