### ISSUE TITLE
db - stutters and drifts

### ISSUE THREAD

**Issue by aditi-bhaskar** [errorcodexero/swimmy2023#36]
problem:
the drivebase is inconsistent. when the joystick input is to drive in a straight line, the drivebase stutters since the turning/angular swerve modules keep switching angles sporadically. Usually, the onset is after 1-2 seconds of driving straight; usually it happens when driving moderate speeds.
The drivebase also sometimes is "sticky" - after the joystick has been let off, the robot continues it's motion for up to 2 more seconds. This includes driving straight and turning velocities.

It started 2ish pm on Mar 18, and we noticed it as an actual problem closer to 4:40pm

tried solutions (not working)
 - switch gamepads (both don't work)

**Comment by sjcbulldog** [comment]
This was related to the way vision samples were changing the pose of the drive base. The heading was getting changed due to vision samples that where distance enough to be inaccurate.
