### ISSUE TITLE
Abort button not working

### ISSUE THREAD

**Issue by DKassab1425** [errorcodexero/swimmy2023#9]
While using the auto collect mode, the robot did not grab a game object leaving the arm extended with the grabber continuously spinning. After hitting abort, the grabber continued to spin and the arm was still extended, however, control was returned to the driver.

we expected the collect action to cancel and the arms/grabber to return to the stow position.

**Comment by sjcbulldog** [comment]
I assume this was before we worked on the abort functionality.  I think abort is working as expected now.  If not, place add details of what was expected and how it behaved differently.
